title: Weikai's blog.
author: Weikai Mao
email: maoweikai123@outlook.com
description: # this means to ignore newlines until "show_exerpts:"
  Weikai(Walker) Mao's personal blog.
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Weikai Mao
  tagline: maoweikai123@outlook.com
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  show_excerpts: true
  post-categories:
    - categ: "All"
      url: ""
    - categ: "CS"
      url: "categories/cs"
    - categ: "CV"
      url: "categories/cv"
    - categ: "DL"
      url: "categories/dl"
    - categ: "FE"
      url: "categories/fe"
    - categ: "Math"
      url: "categories/math"
    - categ: "ML"
      url: "categories/ml"
    - categ: "NLP"
      url: "categories/nlp"
    - categ: "Stat"
      url: "categories/stat"
    - categ: "杂"
      url: "categories/杂"


  # generate social links in footer
  social_links:
    github: WalkerMao
    linkedIn: in/weikai-mao-000249124
    wechat: /wechat-qr-code.html
    # twitter: ttqrzt7szod3l87
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # Mastodon instances
    mastodon:
    - username: jekyll
      instance: example.com
    - username: jekyll2
      instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# Build settings
# theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 20
paginate_path: "/posts/page:num/"

permalink: /:title:output_ext
